- hosts: ans
  vars: 
    user: tony
  tasks:
   - name: create user {{user}}
     ansible.builtin.user:
      name: "{{user}}"
      password: "rKSo09mD/a81."
      shell: /bin/bash
      groups: sudo
  
# mkpasswd