- hosts: ans
  vars:
    - ansible_python_interpreter: /usr/bin/python3
  tasks:
    # - name: Install Docker Module for Python
    #   pip:
    #     name: docker-compose
    # - name: copy Docker Compose files
    #   copy:
    #     src: ./docker-compose
    #     dest: /home/{{ansible_user}}/
    #     mode: 0644

    - name: install wordpress
      shell: docker-compose up -f ./docker-compose/docker-compose.yaml
